version: '2'
linters:
  default: none
  enable:
    # defaults
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # addons
    - gocyclo
    - revive
    - whitespace
    - wsl
    # - funlen
