global:
  scrape_interval: "5m"
  scrape_timeout: "10s"
  evaluation_interval: "1m"

scrape_configs:
  - job_name: ksei-exporter
    metrics_path: /metrics
    honor_labels: true
    honor_timestamps: true
    static_configs:
      - targets:
          - ksei-exporter:8080
